/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Встречи
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meeting implements Serializable {

    private static final long serialVersionUID = -2142831553;

    private Long      meetingId;
    private String    name;
    private String    place;
    private Timestamp startDate;
    private String    description;

    public Meeting() {}

    public Meeting(Meeting value) {
        this.meetingId = value.meetingId;
        this.name = value.name;
        this.place = value.place;
        this.startDate = value.startDate;
        this.description = value.description;
    }

    public Meeting(
        Long      meetingId,
        String    name,
        String    place,
        Timestamp startDate,
        String    description
    ) {
        this.meetingId = meetingId;
        this.name = name;
        this.place = place;
        this.startDate = startDate;
        this.description = description;
    }

    public Long getMeetingId() {
        return this.meetingId;
    }

    public void setMeetingId(Long meetingId) {
        this.meetingId = meetingId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPlace() {
        return this.place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public Timestamp getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Meeting (");

        sb.append(meetingId);
        sb.append(", ").append(name);
        sb.append(", ").append(place);
        sb.append(", ").append(startDate);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
