/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Уведомления, пользователи проверяют эту таблицу на наличия уведомлений 
 * об изменении встреч.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notification implements Serializable {

    private static final long serialVersionUID = -1621478040;

    private Long      notificationId;
    private Long      appUserId;
    private Boolean   isRead;
    private String    messageText;
    private Timestamp createDate;

    public Notification() {}

    public Notification(Notification value) {
        this.notificationId = value.notificationId;
        this.appUserId = value.appUserId;
        this.isRead = value.isRead;
        this.messageText = value.messageText;
        this.createDate = value.createDate;
    }

    public Notification(
        Long      notificationId,
        Long      appUserId,
        Boolean   isRead,
        String    messageText,
        Timestamp createDate
    ) {
        this.notificationId = notificationId;
        this.appUserId = appUserId;
        this.isRead = isRead;
        this.messageText = messageText;
        this.createDate = createDate;
    }

    public Long getNotificationId() {
        return this.notificationId;
    }

    public void setNotificationId(Long notificationId) {
        this.notificationId = notificationId;
    }

    public Long getAppUserId() {
        return this.appUserId;
    }

    public void setAppUserId(Long appUserId) {
        this.appUserId = appUserId;
    }

    public Boolean getIsRead() {
        return this.isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    public String getMessageText() {
        return this.messageText;
    }

    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Notification (");

        sb.append(notificationId);
        sb.append(", ").append(appUserId);
        sb.append(", ").append(isRead);
        sb.append(", ").append(messageText);
        sb.append(", ").append(createDate);

        sb.append(")");
        return sb.toString();
    }
}
