/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * пользователи приложения
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUser implements Serializable {

    private static final long serialVersionUID = 102929729;

    private Long      userId;
    private String    phoneNumber;
    private String    authorizationToken;
    private String    firstName;
    private Integer   lastName;
    private Integer   age;
    private Timestamp birthdayDate;

    public AppUser() {}

    public AppUser(AppUser value) {
        this.userId = value.userId;
        this.phoneNumber = value.phoneNumber;
        this.authorizationToken = value.authorizationToken;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.age = value.age;
        this.birthdayDate = value.birthdayDate;
    }

    public AppUser(
        Long      userId,
        String    phoneNumber,
        String    authorizationToken,
        String    firstName,
        Integer   lastName,
        Integer   age,
        Timestamp birthdayDate
    ) {
        this.userId = userId;
        this.phoneNumber = phoneNumber;
        this.authorizationToken = authorizationToken;
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.birthdayDate = birthdayDate;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getAuthorizationToken() {
        return this.authorizationToken;
    }

    public void setAuthorizationToken(String authorizationToken) {
        this.authorizationToken = authorizationToken;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public Integer getLastName() {
        return this.lastName;
    }

    public void setLastName(Integer lastName) {
        this.lastName = lastName;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Timestamp getBirthdayDate() {
        return this.birthdayDate;
    }

    public void setBirthdayDate(Timestamp birthdayDate) {
        this.birthdayDate = birthdayDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppUser (");

        sb.append(userId);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(authorizationToken);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(age);
        sb.append(", ").append(birthdayDate);

        sb.append(")");
        return sb.toString();
    }
}
