/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Участники встречи
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeetingUserHref implements Serializable {

    private static final long serialVersionUID = -1914504447;

    private Long    meetingUserHrefId;
    private Long    meetingId;
    private Long    appUserId;
    private Boolean isOrganizer;

    public MeetingUserHref() {}

    public MeetingUserHref(MeetingUserHref value) {
        this.meetingUserHrefId = value.meetingUserHrefId;
        this.meetingId = value.meetingId;
        this.appUserId = value.appUserId;
        this.isOrganizer = value.isOrganizer;
    }

    public MeetingUserHref(
        Long    meetingUserHrefId,
        Long    meetingId,
        Long    appUserId,
        Boolean isOrganizer
    ) {
        this.meetingUserHrefId = meetingUserHrefId;
        this.meetingId = meetingId;
        this.appUserId = appUserId;
        this.isOrganizer = isOrganizer;
    }

    public Long getMeetingUserHrefId() {
        return this.meetingUserHrefId;
    }

    public void setMeetingUserHrefId(Long meetingUserHrefId) {
        this.meetingUserHrefId = meetingUserHrefId;
    }

    public Long getMeetingId() {
        return this.meetingId;
    }

    public void setMeetingId(Long meetingId) {
        this.meetingId = meetingId;
    }

    public Long getAppUserId() {
        return this.appUserId;
    }

    public void setAppUserId(Long appUserId) {
        this.appUserId = appUserId;
    }

    public Boolean getIsOrganizer() {
        return this.isOrganizer;
    }

    public void setIsOrganizer(Boolean isOrganizer) {
        this.isOrganizer = isOrganizer;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MeetingUserHref (");

        sb.append(meetingUserHrefId);
        sb.append(", ").append(meetingId);
        sb.append(", ").append(appUserId);
        sb.append(", ").append(isOrganizer);

        sb.append(")");
        return sb.toString();
    }
}
