/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.bur.domain.db.tables.Notification;
import ru.bur.domain.db.tables.records.NotificationRecord;


/**
 * Уведомления, пользователи проверяют эту таблицу на наличия уведомлений 
 * об изменении встреч.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationDao extends DAOImpl<NotificationRecord, ru.bur.domain.db.tables.pojos.Notification, Long> {

    /**
     * Create a new NotificationDao without any configuration
     */
    public NotificationDao() {
        super(Notification.NOTIFICATION, ru.bur.domain.db.tables.pojos.Notification.class);
    }

    /**
     * Create a new NotificationDao with an attached configuration
     */
    public NotificationDao(Configuration configuration) {
        super(Notification.NOTIFICATION, ru.bur.domain.db.tables.pojos.Notification.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(ru.bur.domain.db.tables.pojos.Notification object) {
        return object.getNotificationId();
    }

    /**
     * Fetch records that have <code>notification_id IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Notification> fetchByNotificationId(Long... values) {
        return fetch(Notification.NOTIFICATION.NOTIFICATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>notification_id = value</code>
     */
    public ru.bur.domain.db.tables.pojos.Notification fetchOneByNotificationId(Long value) {
        return fetchOne(Notification.NOTIFICATION.NOTIFICATION_ID, value);
    }

    /**
     * Fetch records that have <code>app_user_id IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Notification> fetchByAppUserId(Long... values) {
        return fetch(Notification.NOTIFICATION.APP_USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_read IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Notification> fetchByIsRead(Boolean... values) {
        return fetch(Notification.NOTIFICATION.IS_READ, values);
    }

    /**
     * Fetch records that have <code>message_text IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Notification> fetchByMessageText(String... values) {
        return fetch(Notification.NOTIFICATION.MESSAGE_TEXT, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Notification> fetchByCreateDate(Timestamp... values) {
        return fetch(Notification.NOTIFICATION.CREATE_DATE, values);
    }
}
