/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ru.bur.domain.db.tables.AppUser;
import ru.bur.domain.db.tables.Meeting;


/**
 * A class modelling indexes of tables of the <code>base_schema</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APP_USER_AUTHORIZATION_TOKEN_UINDEX = Indexes0.APP_USER_AUTHORIZATION_TOKEN_UINDEX;
    public static final Index APP_USER_PHONE_NUMBER_UINDEX = Indexes0.APP_USER_PHONE_NUMBER_UINDEX;
    public static final Index APP_USER_PK = Indexes0.APP_USER_PK;
    public static final Index APP_USER_USER_ID_UINDEX = Indexes0.APP_USER_USER_ID_UINDEX;
    public static final Index MEETING_MEETING_ID_UINDEX = Indexes0.MEETING_MEETING_ID_UINDEX;
    public static final Index MEETING_PK = Indexes0.MEETING_PK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index APP_USER_AUTHORIZATION_TOKEN_UINDEX = Internal.createIndex("app_user_authorization_token_uindex", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.AUTHORIZATION_TOKEN }, true);
        public static Index APP_USER_PHONE_NUMBER_UINDEX = Internal.createIndex("app_user_phone_number_uindex", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.PHONE_NUMBER }, true);
        public static Index APP_USER_PK = Internal.createIndex("app_user_pk", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.USER_ID }, true);
        public static Index APP_USER_USER_ID_UINDEX = Internal.createIndex("app_user_user_id_uindex", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.USER_ID }, true);
        public static Index MEETING_MEETING_ID_UINDEX = Internal.createIndex("meeting_meeting_id_uindex", Meeting.MEETING, new OrderField[] { Meeting.MEETING.MEETING_ID }, true);
        public static Index MEETING_PK = Internal.createIndex("meeting_pk", Meeting.MEETING, new OrderField[] { Meeting.MEETING.MEETING_ID }, true);
    }
}
