/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.bur.domain.db.tables.AppUser;
import ru.bur.domain.db.tables.Meeting;
import ru.bur.domain.db.tables.records.AppUserRecord;
import ru.bur.domain.db.tables.records.MeetingRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>base_schema</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MeetingRecord, Long> IDENTITY_MEETING = Identities0.IDENTITY_MEETING;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppUserRecord> APP_USER_PK = UniqueKeys0.APP_USER_PK;
    public static final UniqueKey<MeetingRecord> MEETING_PK = UniqueKeys0.MEETING_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<MeetingRecord, Long> IDENTITY_MEETING = Internal.createIdentity(Meeting.MEETING, Meeting.MEETING.MEETING_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AppUserRecord> APP_USER_PK = Internal.createUniqueKey(AppUser.APP_USER, "app_user_pk", AppUser.APP_USER.USER_ID);
        public static final UniqueKey<MeetingRecord> MEETING_PK = Internal.createUniqueKey(Meeting.MEETING, "meeting_pk", Meeting.MEETING.MEETING_ID);
    }
}
