/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in base_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>base_schema.meeting_meeting_id_seq</code>
     */
    public static final Sequence<Long> MEETING_MEETING_ID_SEQ = new SequenceImpl<Long>("meeting_meeting_id_seq", BaseSchema.BASE_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
