/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.bur.domain.db.tables.Notification;


/**
 * Уведомления, пользователи проверяют эту таблицу на наличия уведомлений 
 * об изменении встреч.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationRecord extends UpdatableRecordImpl<NotificationRecord> implements Record5<Long, Long, Boolean, String, Timestamp> {

    private static final long serialVersionUID = 737847089;

    /**
     * Setter for <code>base_schema.notification.notification_id</code>.
     */
    public void setNotificationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>base_schema.notification.notification_id</code>.
     */
    public Long getNotificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>base_schema.notification.app_user_id</code>. пользователь, который должен получить уведомление
     */
    public void setAppUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>base_schema.notification.app_user_id</code>. пользователь, который должен получить уведомление
     */
    public Long getAppUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>base_schema.notification.is_read</code>. true, если сообщение было прочитано пользователем.
     */
    public void setIsRead(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>base_schema.notification.is_read</code>. true, если сообщение было прочитано пользователем.
     */
    public Boolean getIsRead() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>base_schema.notification.message_text</code>. Текст уведомления
     */
    public void setMessageText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>base_schema.notification.message_text</code>. Текст уведомления
     */
    public String getMessageText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>base_schema.notification.create_date</code>. Дата создания
     */
    public void setCreateDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>base_schema.notification.create_date</code>. Дата создания
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Boolean, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Boolean, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Notification.NOTIFICATION.NOTIFICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Notification.NOTIFICATION.APP_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Notification.NOTIFICATION.IS_READ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Notification.NOTIFICATION.MESSAGE_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Notification.NOTIFICATION.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getNotificationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAppUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getIsRead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMessageText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getNotificationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAppUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getIsRead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMessageText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value1(Long value) {
        setNotificationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value2(Long value) {
        setAppUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value3(Boolean value) {
        setIsRead(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value4(String value) {
        setMessageText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value5(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord values(Long value1, Long value2, Boolean value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationRecord
     */
    public NotificationRecord() {
        super(Notification.NOTIFICATION);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(Long notificationId, Long appUserId, Boolean isRead, String messageText, Timestamp createDate) {
        super(Notification.NOTIFICATION);

        set(0, notificationId);
        set(1, appUserId);
        set(2, isRead);
        set(3, messageText);
        set(4, createDate);
    }
}
