/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.bur.domain.db.tables.AppUser;


/**
 * пользователи приложения
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> implements Record7<Long, String, String, String, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -1472114408;

    /**
     * Setter for <code>base_schema.app_user.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>base_schema.app_user.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>base_schema.app_user.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>base_schema.app_user.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>base_schema.app_user.authorization_token</code>.
     */
    public void setAuthorizationToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>base_schema.app_user.authorization_token</code>.
     */
    public String getAuthorizationToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>base_schema.app_user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>base_schema.app_user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>base_schema.app_user.last_name</code>.
     */
    public void setLastName(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>base_schema.app_user.last_name</code>.
     */
    public Integer getLastName() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>base_schema.app_user.age</code>.
     */
    public void setAge(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>base_schema.app_user.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>base_schema.app_user.birthday_date</code>.
     */
    public void setBirthdayDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>base_schema.app_user.birthday_date</code>.
     */
    public Timestamp getBirthdayDate() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Integer, Integer, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Integer, Integer, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AppUser.APP_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AppUser.APP_USER.PHONE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AppUser.APP_USER.AUTHORIZATION_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AppUser.APP_USER.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return AppUser.APP_USER.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return AppUser.APP_USER.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return AppUser.APP_USER.BIRTHDAY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAuthorizationToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getBirthdayDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAuthorizationToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getBirthdayDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRecord value2(String value) {
        setPhoneNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRecord value3(String value) {
        setAuthorizationToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRecord value5(Integer value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRecord value6(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRecord value7(Timestamp value) {
        setBirthdayDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRecord values(Long value1, String value2, String value3, String value4, Integer value5, Integer value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserRecord
     */
    public AppUserRecord() {
        super(AppUser.APP_USER);
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(Long userId, String phoneNumber, String authorizationToken, String firstName, Integer lastName, Integer age, Timestamp birthdayDate) {
        super(AppUser.APP_USER);

        set(0, userId);
        set(1, phoneNumber);
        set(2, authorizationToken);
        set(3, firstName);
        set(4, lastName);
        set(5, age);
        set(6, birthdayDate);
    }
}
