/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.bur.domain.db.tables.MeetingUserHref;
import ru.bur.domain.db.tables.records.MeetingUserHrefRecord;


/**
 * Участники встречи
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeetingUserHrefDao extends DAOImpl<MeetingUserHrefRecord, ru.bur.domain.db.tables.pojos.MeetingUserHref, Long> {

    /**
     * Create a new MeetingUserHrefDao without any configuration
     */
    public MeetingUserHrefDao() {
        super(MeetingUserHref.MEETING_USER_HREF, ru.bur.domain.db.tables.pojos.MeetingUserHref.class);
    }

    /**
     * Create a new MeetingUserHrefDao with an attached configuration
     */
    public MeetingUserHrefDao(Configuration configuration) {
        super(MeetingUserHref.MEETING_USER_HREF, ru.bur.domain.db.tables.pojos.MeetingUserHref.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(ru.bur.domain.db.tables.pojos.MeetingUserHref object) {
        return object.getMeetingUserHrefId();
    }

    /**
     * Fetch records that have <code>meeting_user_href_id IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.MeetingUserHref> fetchByMeetingUserHrefId(Long... values) {
        return fetch(MeetingUserHref.MEETING_USER_HREF.MEETING_USER_HREF_ID, values);
    }

    /**
     * Fetch a unique record that has <code>meeting_user_href_id = value</code>
     */
    public ru.bur.domain.db.tables.pojos.MeetingUserHref fetchOneByMeetingUserHrefId(Long value) {
        return fetchOne(MeetingUserHref.MEETING_USER_HREF.MEETING_USER_HREF_ID, value);
    }

    /**
     * Fetch records that have <code>meeting_id IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.MeetingUserHref> fetchByMeetingId(Long... values) {
        return fetch(MeetingUserHref.MEETING_USER_HREF.MEETING_ID, values);
    }

    /**
     * Fetch records that have <code>app_user_id IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.MeetingUserHref> fetchByAppUserId(Long... values) {
        return fetch(MeetingUserHref.MEETING_USER_HREF.APP_USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_organizer IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.MeetingUserHref> fetchByIsOrganizer(Boolean... values) {
        return fetch(MeetingUserHref.MEETING_USER_HREF.IS_ORGANIZER, values);
    }
}
