/*
 * This file is generated by jOOQ.
*/
package ru.bur.domain.db.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.bur.domain.db.tables.Meeting;
import ru.bur.domain.db.tables.records.MeetingRecord;


/**
 * Встречи
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeetingDao extends DAOImpl<MeetingRecord, ru.bur.domain.db.tables.pojos.Meeting, Long> {

    /**
     * Create a new MeetingDao without any configuration
     */
    public MeetingDao() {
        super(Meeting.MEETING, ru.bur.domain.db.tables.pojos.Meeting.class);
    }

    /**
     * Create a new MeetingDao with an attached configuration
     */
    public MeetingDao(Configuration configuration) {
        super(Meeting.MEETING, ru.bur.domain.db.tables.pojos.Meeting.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(ru.bur.domain.db.tables.pojos.Meeting object) {
        return object.getMeetingId();
    }

    /**
     * Fetch records that have <code>meeting_id IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Meeting> fetchByMeetingId(Long... values) {
        return fetch(Meeting.MEETING.MEETING_ID, values);
    }

    /**
     * Fetch a unique record that has <code>meeting_id = value</code>
     */
    public ru.bur.domain.db.tables.pojos.Meeting fetchOneByMeetingId(Long value) {
        return fetchOne(Meeting.MEETING.MEETING_ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Meeting> fetchByName(String... values) {
        return fetch(Meeting.MEETING.NAME, values);
    }

    /**
     * Fetch records that have <code>place IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Meeting> fetchByPlace(String... values) {
        return fetch(Meeting.MEETING.PLACE, values);
    }

    /**
     * Fetch records that have <code>start_date IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Meeting> fetchByStartDate(Timestamp... values) {
        return fetch(Meeting.MEETING.START_DATE, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<ru.bur.domain.db.tables.pojos.Meeting> fetchByDescription(String... values) {
        return fetch(Meeting.MEETING.DESCRIPTION, values);
    }
}
